### ISSUE TITLE
Apple Pay in Safari doesn't work when MacGesture is running

### ISSUE THREAD

**Issue by Morac2** [MacGesture/MacGesture#110]
I found that Apple Pay in Safari doesn't work when MacGesture is running.  I installed version 3.0.0 using homebrew on April 30 on my MacBook Air 2020 (M1) to enable using mouse gestures in Safari.  I noticed Apple Pay wasn't working, but didn't look into to it till today when I discovered that as long as MacGesture is running, Apple Pay will fail to proceed after using Touch ID or password to actually do the payment.

Steps to reproduce:

1.  Create Gestures for Safari (see screen shot for ones I added).
2. Have MacGesture running.
3. Go to https://applepaydemo.apple.com and attempt to complete the Apple Pay Demo.

Expected result:

Apple Pay should work.

Actual result:

Apple Pay won't proceed past the pay with Touch ID or password step.  The only option is to cancel.

Work around:

Quit MacGesture.

<img width="660" alt="Screen Shot 2021-10-28 at 12 32 52 PM" src="https://user-images.githubusercontent.com/1596194/139297895-e1018d2d-63e0-4672-8af0-bd29d233cc86.png">

**Comment by username0x0a** [comment]
Safari specifically is quite secured to various screen grabbing & clicking software – it explicitly maps 3rd-party apps' windows to detect possibly colliding layers that could cause such software to manipulate with mouse events in Safari. Because of that exactly, when using MacGesture, there's a special prompt when enabling Safari extensions so that you need to confirm such action. I wouldn't be surprised if Apple also secures payment dialogs to behave in some manner when a clicking software like MacGesture _potentially_ is, operates on top of Safari windows.

**Comment by Morac2** [comment]
I have Safari extensions enabled (first thing I tried disabling) and they don’t prevent Apple Pay.  The thing is, this has nothing to do with mouse clicking.  It seems to block access to the secure T2 chip where the payment info is stored once Apple Pay is authorized using Touch ID or a password.  It also doesn’t matter if Safari is mapped or not.

**Comment by username0x0a** [comment]
Sorry, maybe my brief description was hard to put in context. Neither the extensions nor the mapping are of a trouble here.

The thing is, Safari detects MacGesture (in general, any app conforming to some rules) as an app which draws a fullscreen window (both for gesture drawing and right mouse click events capturing). This window overflows Safari windows (so that we can capture, process & forward right mouse clicks), thus MacGesture is detected as _potentially_ troubling app – f.e. some harmful application could draw some custom stuff (fake “Click me” buttons, etc.) as well as invoke artificial mouse clicks (thanks to the accessibility permission) leading to fake payments, enabling harmful extensions, etc.

Because of this detection, Safari may prevent user from:

- using Apple Pay
  - although confirmation via Apple Watch or iPhone works, if possible
- enabling Extensions
  - additional prompt is displayed to the user when enabling random Extension
  - some early Safari versions only logged a Console message with no prompt, causing the Extensions not to be turnable at all until MacGesture was quitted

as long as the invisible capture/drawing window of MacGesture is present, in other words, as long as it's running.

Maybe some temporary disabling (via Menu bar menu) could be done, though. 🤔

**Comment by username0x0a** [comment]
Here's a demonstration of the feature:

https://user-images.githubusercontent.com/5228484/140577342-e274e26b-f483-4a37-a88a-80a556175d15.mov

Interestingly enough, Safari even detects native Screen capture as a fraud tool 😆 so I can't really show you it works okay when MacGesture is shut down.

**Comment by username0x0a** [comment]
Here's a demonstration of the feature:

https://user-images.githubusercontent.com/5228484/140578112-c8c98bc0-9b53-4b0d-af03-444a67af222e.mov

Interestingly enough, Safari even detects native Screen capture as a fraud tool 😆 so I can't really show you it works okay when MacGesture is shut down.
