### ISSUE TITLE
MacGesture prevent to connect to VPN

### ISSUE THREAD

**Issue by alezzblezz** [MacGesture/MacGesture#123]
Since Monterey 12.4 (MBA M1), if MacGesture (v3.1.0) is started, I can't connect to my work's VPN (Cisco IpSec,   AuthenticationMethod = SharedSecret).

1. MacGesture is started
2. Preferences > Network > my work's VPN > Connect
3. Window is opened with username and password
4. When clicking on "OK" or "Cancel", nothing happens (and connexion expires after a time)
5. If I quit MacGesture, "OK" or "Cancel" buttons works as they might do

- MacBook Air M1
- MacOS Monterey 12.4
- MacGesture 3.1.0

**Comment by alezzblezz** [comment]
Add : 

Cannot click on "OK" in the window shown when VPN session expires. Same way.

**Comment by alezzblezz** [comment]
Nope. This happens with the integrated MacOs VPN client.

Add : 

Bug reproduced with all windows from Preferences. I tried to add following lines in block list, with no success : 

com.apple.preference.network.*
/System/Applications/System Preferences.app/*

**Comment by godfather1103** [comment]
I also have this bug. It seems that the pop-up window of the user notification center will have this bug.

**Comment by godfather1103** [comment]
![b371ddce-3ec8-483e-8762-00b6d5765bea](https://user-images.githubusercontent.com/11797964/172013467-eb5a2a41-8572-416a-94d4-98d8ea7f0ea3.gif)

**Comment by seagle0128** [comment]
Same issue here. All dialogs of notification center cannot be clicked, on both M1 and x86 macOS 12.4.

**Comment by godfather1103** [comment]
12.5 seems to be repaired

**Comment by username0x0a** [comment]
There's a system security feature (since Mojave or so) that basically checks whether the screen is covered by some 3rd-party app's layer, which is exactly what MacGesture does – it covers the screen with a transparent window layer used to detect clicks & draw gesture previews if enabled.

In Safari for example, this results in an additional dialog being displayed when you attempt to turn on some new extension. I think I've seen it on some other places in Preferences as well.

We can't really do anything about it. The OS should alert user in case this detection kicks in, as the Safari mentioned does. Hoping that Monterey 12.5 fixes that behaviour, otherwise temporarily quitting/disabling MacGesture should help as well.
